name: deploy
on: 
  push:
    branches: ["main"]
  workflow_dispatch:
jobs:
  Deploy:
    uses: seanh/ghp-pelican/.github/workflows/pelican.yml@main
    permissions:
      content: read
      pages: write
      id-token: write
    with:
      settings: "publishconf.py"
      requirements: "pelican[markdown] pelican-render-math typografy"
      theme: "https://github.com/alexandrevicenzi/Flex.git"